export const copy = {
  en: {
    title: "Store Ordering",
    weeklyPicksHero: "Current promotions for your store. Tap + to add cases to your cart.",
    addAllWeeklyPicksOneCase: "Add 1 case of each promotion",
    addAllClearanceOneCase: "Add 1 case of each Near Date Sale item",
    missingWeeklyPicksTitle: "Promotions not in your cart yet",
    missingClearancePicksTitle: "Near Date Sale deals not in your cart yet",
    addAllMissingPicks: "Add all ({count}) · 1 case each",
    addOneCase: "+ 1 case",
    recommendedStripTitle: "Suggested for you",
    hideSuggested: "Hide",
    showSuggested: "Show suggested",
    addMissingPicksBar: "Add {count} promotions (+1 each)",
    addMissingClearanceBar: "Add {count} Near Date Sale (+1 each)",
    roundUpBogo: "Complete deal set ({pack} cases)",
    quickAddSelected: "Set qty on selected SKU",
    jumpToCart: "View cart",
    modeTabMissing: "+{count}",
    postSubmitAddAll: "Add all ({count}) · 1 case each",
    cartSalesSummary: "{weekly} promo · {clearance} Near Date Sale",
    postSubmitSuggestTitle: "Before your next order",
    postSubmitSuggestHint: "These promotions are still available — add a case now to start your next draft.",
    browseMoreWeeklyPicks: "Browse promotions",
    logout: "Logout",
    customerInfo: "Customer Info",
    show: "Show",
    hide: "Hide",
    phone: "Phone (Optional)",
    orderEmail: "Order email",
    orderEmailHint: "Orders are sent to this address. Default: elin@rheebros.com",
    orderEmailInvalid: "Please enter a valid email address.",
    note: "Note (Optional)",
    searchMode: "Quick order",
    searchModeHint: "Type SKU, UPC, or name — tap a match, set qty, and add to cart.",
    quickOrderEmptyHint: "Type or scan a SKU in the search bar above.",
    quickOrderPickSku: "Tap a match below or press Add.",
    quickOrderMatches: "{count} matches",
    quickOrderShowMore: "Show {count} more",
    quickOrderShowLess: "Show fewer",
    quickOrderKeyboardHint: "↑↓ pick a match · +/- qty · Enter add to cart",
    quickOrderFrequent: "Often on your invoices",
    quickOrderPicks: "Quick picks",
    catalogMode: "Catalog order",
    promotionMode: "Promotions",
    newItemsMode: "New items",
    newItemsHero: "Only SKUs you mark as New items in Admin. Red JUST ADDED only on SKUs you check JUST ADDED in Products.",
    noNewItems: "No new items right now.",
    addAllNewItemsOneCase: "Add 1 case of each new item",
    promotionHint: "Featured promotions — add cases to your cart.",
    loadingPromotions: "Loading promotions...",
    noPromotions: "No promotions configured yet.",
    promoBadge: "SALE",
    promoPrice: "Promo price",
    promoRemaining: "Left",
    promoSoldOut: "Sold out",
    promoDateRange: "Valid",
    promoBuyXGetY: "Buy {buy} Get {free} FREE",
    promoVolumeTiers: "Volume Sale",
    promoBuyXGetYPackHint: "Deal = {pack} cases per set (buy + free)",
    promoBogoQtyWarning: "{sku}: Buy {buy} Get {free} free — qty {qty} is not a full set of {pack} cases.",
    promoTierQtyWarning: "{sku}: Qty {qty} is below the lowest volume tier ({min} {cs}).",
    casesAbbr: "cs",
    promoQtyLimit: "Promo limit",
    promoLimitAlert: "Only {qty} promo cases left for {sku}.",
    promoReviewReminder: "You haven't added any promotions yet. Browse them before submitting?",
    viewPromotions: "Browse promotions",
    clearanceMode: "Near Date Sale",
    clearanceHint: "Near-expiry sell-as-is items — expiry date and price shown. Final sale: no return, no refund.",
    loadingClearance: "Loading Near Date Sale items...",
    noClearance: "No Near Date Sale items right now.",
    clearanceBadge: "SELL AS IS",
    clearanceNoReturn: "No return · No refund",
    clearancePolicyReviewNote: "This order includes Near Date Sale items — final sale, no returns or refunds.",
    clearancePrice: "Near Date Sale price",
    invoicePrice: "Your price",
    clearanceExpiry: "Expires",
    clearanceRemaining: "Left",
    clearanceSoldOut: "Sold out",
    clearanceDaysLeft: "{days} days left",
    clearanceQtyLimit: "Stock limit",
    clearanceLimitAlert: "Only {qty} Near Date Sale cases left for {sku}.",
    clearanceReviewReminder: "There are {count} Near Date Sale deals available. Check them before submitting?",
    viewClearance: "View Near Date Sale",
    clearanceQtyWarning: "{sku} Near Date Sale stock left is {qty}.",
    newItemsReviewReminder: "There are {count} new items available. Want to check them before submitting?",
    viewNewItems: "View new items",
    addItems: "Quick order",
    availableOnly: "Show available items only",
    favoritesOnly: "Favorites only",
    addFavorite: "Add to favorites",
    removeFavorite: "Remove from favorites",
    noFavorites: "No favorites yet. Tap the star on any SKU to save it here.",
    skuItem: "SKU / Item",
    qty: "Qty",
    addItem: "Add to cart",
    catalogSearch: "Search all products...",
    recent: "Frequently ordered",
    history: "Past orders",
    historyChipHint: "Tap to reorder from your previous orders",
    historyModalHint: "Pick an order and tap Order again to add it to your cart.",
    reorder: "Order again",
    orderCart: "Your cart",
    noItems: "No items added yet.",
    clearAll: "Clear All",
    clearOrder: "Clear Order",
    remove: "Remove",
    downloadCsv: "Download CSV",
    uploadCsv: "Upload CSV",
    submitOrder: "Confirm order",
    submitting: "Placing order...",
    unavailable: "This item is currently unavailable",
    orderNotAvailable: "Not available",
    enterSku: "Please enter SKU.",
    duplicate: "is already in cart.\n\nDo you want to add it again?",
    clearConfirm: "Please confirm clear current order.",
    cleared: "Current order cleared.",
    addAtLeast: "Please add at least one item.",
    submitConfirm: "Place this order?",
    accountNo: "Account",
    storeName: "Store",
    items: "Items",
    ref: "Ref",
    loadedDraft: "Last saved draft loaded.",
    csvEmpty: "CSV is empty.",
    noValidRows: "No valid orderable SKU/Qty rows found.",
    orderSuccess: "Order placed successfully.",
    failedSubmit: "Failed to place order.",
    size: "Size",
    limited: "Limited",
    pallet: "Pallet size",
    selected: "Selected",
    allOrderable: "Catalog order",
    noMatches: "No items match your search.",
    tapAdd: "Tap Add or press Enter",
    add: "Add",
    inCart: "In cart",
    selectedOnly: "In cart only",
    showing: "Showing",
    loadMore: "Load more",
    cartSummary: "Cart",
    cases: "cases",
    lines: "lines",
    reviewCart: "Review cart",
    reviewOrder: "Review your order",
    reviewWarnings: "Please double-check",
    reviewWarningsHint: "You can still place your order — adjust qty if needed.",
    skipSection: "Skip",
    skipWeeklyUpsell: "Skip promotions",
    skipClearanceUpsell: "Skip Near Date Sale suggestions",
    highQtyWarning: "{sku} has a large qty: {qty}.",
    limitedQtyWarning: "{sku} limited qty is {qty}.",
    promoQtyWarning: "{sku} promo left is {qty}.",
    statusWarning: "{sku} status is {status}.",
    unavailableMissingSku: "{sku} was not found in the catalog.",
    unavailableInCartTitle: "Some items can't be ordered",
    unavailableInCartHint:
      "These SKUs are discontinued or otherwise unavailable (only NORMAL / TBD can be ordered). Remove them to place your order — the rest of your cart can still be submitted.",
    removeUnavailable: "Remove unavailable items",
    removeUnavailableAndSubmit: "Remove them & place order",
    confirmSubmitBlocked: "Remove unavailable items first",
    unavailableRemoved: "Removed {count} unavailable item(s).",
    confirmSubmit: "Confirm & place order",
    orderSubmitted: "Order placed",
    done: "Done",
    showCart: "Show cart",
    hideCart: "Hide cart",
    searchPlaceholder: "SKU, UPC, name, brand, or barcode",
    catalogCount: "products",
    quickAdd: "Quick add",
    close: "Close",
    back: "Back",
    brand: "Brand",
    allBrands: "All brands",
    category: "Category",
    recommended: "Recommended for you",
    newItems: "New items",
    listPrice: "List price",
    justAdded: "JUST ADDED",
    addedDate: "Added",
    publishedDate: "Published",
    comingDate: "Coming",
    showFilters: "Filters",
    hideFilters: "Hide filters",
    editProduct: "Edit",
    viewDetails: "View",
    hideDetails: "Hide",
    moreBrandsPick: "More brands…",
    enterFullscreen: "Full screen",
    exitFullscreen: "Exit full screen",
    scanBarcode: "Scan barcode",
    scanBarcodeTitle: "Scan barcode",
    scanBarcodeHint: "Center the barcode in the frame and hold steady. Move closer if it does not scan.",
    scanBarcodeCameraError: "Could not access the camera. Check permissions or type the code manually.",
    scanBarcodeTorchOn: "Turn on light",
    scanBarcodeTorchOff: "Turn off light",
  },
  zh: {
    title: "门店订货",
    weeklyPicksHero: "当前促销商品，点 + 按箱加入购物车。",
    addAllWeeklyPicksOneCase: "各加 1 箱（全部促销）",
    addAllClearanceOneCase: "各加 1 箱（全部临期）",
    missingWeeklyPicksTitle: "购物车还没有这些促销商品",
    missingClearancePicksTitle: "购物车还没有这些临期特价",
    addAllMissingPicks: "全部加入（{count} 个 · 各 1 箱）",
    addOneCase: "+ 1 箱",
    recommendedStripTitle: "为你推荐",
    hideSuggested: "隐藏",
    showSuggested: "显示推荐",
    addMissingPicksBar: "加入 {count} 个促销（各 1 箱）",
    addMissingClearanceBar: "加入 {count} 个临期（各 1 箱）",
    roundUpBogo: "凑满一组（{pack} 箱）",
    quickAddSelected: "给当前选中 SKU 设数量",
    jumpToCart: "查看购物车",
    modeTabMissing: "+{count}",
    postSubmitAddAll: "全部加入（{count} 个 · 各 1 箱）",
    cartSalesSummary: "促销 {weekly} · 临期 {clearance}",
    postSubmitSuggestTitle: "下次订货可留意",
    postSubmitSuggestHint: "以下促销仍有货，可现在加 1 箱开始下一单草稿。",
    browseMoreWeeklyPicks: "去看促销",
    logout: "登出",
    customerInfo: "客户信息",
    show: "展开",
    hide: "收起",
    phone: "电话（可选）",
    orderEmail: "订单邮箱",
    orderEmailHint: "订单将发送到此邮箱。默认：elin@rheebros.com",
    orderEmailInvalid: "请输入有效的邮箱地址。",
    note: "备注（可选）",
    searchMode: "快速下单",
    searchModeHint: "输入 SKU、条码或品名 — 点选商品、设数量、加入购物车。",
    quickOrderEmptyHint: "请在上方搜索栏输入或扫描 SKU。",
    quickOrderPickSku: "请点选下方匹配商品，或按「加入购物车」。",
    quickOrderMatches: "匹配 {count} 项",
    quickOrderShowMore: "再显示 {count} 项",
    quickOrderShowLess: "收起",
    quickOrderKeyboardHint: "↑↓ 选择匹配项 · +/- 改数量 · Enter 加入购物车",
    quickOrderFrequent: "发票常购",
    quickOrderPicks: "快捷选品",
    catalogMode: "目录订货",
    promotionMode: "促销",
    newItemsMode: "新品",
    newItemsHero: "仅显示后台勾选「新品」的 SKU。仅勾选 JUST ADDED 的 SKU 显示红色「刚刚上架」。",
    noNewItems: "暂无新品。",
    addAllNewItemsOneCase: "各加 1 箱（全部新品）",
    promotionHint: "精选促销商品，输入箱数加入购物车。",
    loadingPromotions: "正在加载促销商品...",
    noPromotions: "暂无促销活动。",
    promoBadge: "促销",
    promoPrice: "促销价",
    promoRemaining: "剩余",
    promoSoldOut: "已售罄",
    promoDateRange: "有效期",
    promoBuyXGetY: "买 {buy} 送 {free}",
    promoVolumeTiers: "量价优惠",
    promoBuyXGetYPackHint: "每组 {pack} 箱（买 + 送）",
    promoBogoQtyWarning: "{sku}：买 {buy} 送 {free} — 当前 {qty} 箱不是完整的 {pack} 箱一组。",
    promoTierQtyWarning: "{sku}：当前 {qty} 箱未达到最低档量价（{min}{cs} 起）。",
    casesAbbr: "箱",
    promoQtyLimit: "促销限量",
    promoLimitAlert: "{sku} 促销仅剩 {qty} 箱。",
    promoReviewReminder: "购物车还没有促销商品。提交前要不要看一下？",
    viewPromotions: "查看促销",
    clearanceMode: "临期特价",
    clearanceHint: "临期按现状出售商品，显示过期日期与特价。不退不换，请确认后再下单。",
    loadingClearance: "正在加载临期商品...",
    noClearance: "暂无临期商品。",
    clearanceBadge: "临期",
    clearanceNoReturn: "不退不换",
    clearancePolicyReviewNote: "订单含临期商品，不退不换，请确认后再提交。",
    clearancePrice: "特价",
    invoicePrice: "您的价格",
    clearanceExpiry: "过期日",
    clearanceRemaining: "剩余",
    clearanceSoldOut: "已售罄",
    clearanceDaysLeft: "还剩 {days} 天",
    clearanceQtyLimit: "库存限量",
    clearanceLimitAlert: "{sku} 临期仅剩 {qty} 箱。",
    clearanceReviewReminder: "还有 {count} 个临期特价可选。提交前要不要看一下？",
    viewClearance: "查看临期特价",
    clearanceQtyWarning: "{sku} 临期剩余 {qty}。",
    newItemsReviewReminder: "现在有 {count} 个新品。提交前要不要看一下？",
    viewNewItems: "查看新品",
    addItems: "快速下单",
    availableOnly: "只显示可下单商品",
    favoritesOnly: "只看收藏",
    addFavorite: "加入收藏",
    removeFavorite: "取消收藏",
    noFavorites: "还没有收藏。点商品上的星星即可加入。",
    skuItem: "SKU / 商品",
    qty: "数量",
    addItem: "加入购物车",
    catalogSearch: "搜索全部商品...",
    recent: "常订清单",
    history: "历史订单",
    historyChipHint: "点这里重复订购以前的订单",
    historyModalHint: "选择订单后点「再订一次」加入购物车。",
    reorder: "再订一次",
    orderCart: "购物车",
    noItems: "还没有添加商品。",
    clearAll: "清空",
    clearOrder: "清空订单",
    remove: "删除",
    downloadCsv: "下载 CSV",
    uploadCsv: "上传 CSV",
    submitOrder: "确认订货",
    submitting: "提交中...",
    unavailable: "此商品目前无法下单",
    orderNotAvailable: "无法下单",
    enterSku: "请输入 SKU。",
    duplicate: "已经在购物车里。\n\n是否还要再添加一次？",
    clearConfirm: "请确认是否清空当前订单？",
    cleared: "当前订单已清空。",
    addAtLeast: "请至少添加一个商品。",
    submitConfirm: "确定提交这份订货吗？",
    accountNo: "客户账号",
    storeName: "店名",
    items: "商品数",
    ref: "编号",
    loadedDraft: "已载入上次保存的草稿。",
    csvEmpty: "CSV 是空的。",
    noValidRows: "没有找到可下单的有效 SKU/Qty。",
    orderSuccess: "订货提交成功。",
    failedSubmit: "订货提交失败。",
    size: "规格",
    limited: "限量",
    pallet: "板数",
    selected: "已选",
    allOrderable: "目录订货",
    noMatches: "没有找到匹配的商品。",
    tapAdd: "点「添加」或按回车",
    add: "添加",
    inCart: "已选",
    selectedOnly: "只看已选",
    showing: "显示",
    loadMore: "加载更多",
    cartSummary: "购物车",
    cases: "箱",
    lines: "项",
    reviewCart: "核对购物车",
    reviewOrder: "核对订货",
    reviewWarnings: "请再确认",
    reviewWarningsHint: "仍可提交订单，请按需调整箱数。",
    skipSection: "跳过",
    skipWeeklyUpsell: "跳过促销",
    skipClearanceUpsell: "跳过临期推荐",
    highQtyWarning: "{sku} 数量较大：{qty}。",
    limitedQtyWarning: "{sku} 限量为 {qty}。",
    promoQtyWarning: "{sku} 促销剩余 {qty}。",
    statusWarning: "{sku} 状态为 {status}。",
    unavailableMissingSku: "{sku} 在目录中找不到。",
    unavailableInCartTitle: "部分商品无法下单",
    unavailableInCartHint:
      "以下 SKU 无法下单（可下单状态：NORMAL / TBD）。请先删除它们，其余商品仍可正常提交。",
    removeUnavailable: "删除无法下单的商品",
    removeUnavailableAndSubmit: "删除后提交订单",
    confirmSubmitBlocked: "请先删除无法下单的商品",
    unavailableRemoved: "已删除 {count} 个无法下单的商品。",
    confirmSubmit: "确认订货",
    orderSubmitted: "订货已提交",
    done: "完成",
    showCart: "展开购物车",
    hideCart: "收起购物车",
    searchPlaceholder: "SKU、UPC、品名、品牌或条码",
    catalogCount: "个商品",
    quickAdd: "快速添加",
    close: "关闭",
    back: "返回",
    brand: "品牌",
    allBrands: "全部品牌",
    category: "分类",
    recommended: "常买推荐",
    newItems: "新品",
    listPrice: "标价",
    justAdded: "刚刚上架",
    addedDate: "上架",
    publishedDate: "上架",
    comingDate: "到货",
    showFilters: "筛选",
    hideFilters: "收起筛选",
    editProduct: "编辑",
    viewDetails: "查看",
    hideDetails: "收起",
    moreBrandsPick: "更多品牌…",
    enterFullscreen: "全屏",
    exitFullscreen: "退出全屏",
    scanBarcode: "扫码",
    scanBarcodeTitle: "扫描条码",
    scanBarcodeHint: "将条码对准框内并保持平稳，读不出可靠近一些。",
    scanBarcodeCameraError: "无法使用摄像头，请检查权限或改用手动输入。",
    scanBarcodeTorchOn: "打开灯光",
    scanBarcodeTorchOff: "关闭灯光",
  },
  ko: {
    title: "매장 주문",
    weeklyPicksHero: "진행 중인 프로모션 상품입니다. + 로 박스 수량을 담으세요.",
    addAllWeeklyPicksOneCase: "프로모션 전체 각 1박스 추가",
    addAllClearanceOneCase: "임박 전체 각 1박스 추가",
    missingWeeklyPicksTitle: "아직 카트에 없는 프로모션",
    missingClearancePicksTitle: "아직 카트에 없는 임박 특가",
    addAllMissingPicks: "전체 추가 ({count}개 · 각 1박스)",
    addOneCase: "+ 1박스",
    recommendedStripTitle: "추천 상품",
    hideSuggested: "숨기기",
    showSuggested: "추천 보기",
    addMissingPicksBar: "프로모션 {count}개 (+1박스씩)",
    addMissingClearanceBar: "임박 {count}개 (+1박스씩)",
    roundUpBogo: "세트 맞추기 ({pack}박스)",
    quickAddSelected: "선택 SKU 수량 설정",
    jumpToCart: "장바구니 보기",
    modeTabMissing: "+{count}",
    postSubmitAddAll: "전부 추가 ({count}개 · 각 1박스)",
    cartSalesSummary: "프로모션 {weekly} · 임박 {clearance}",
    postSubmitSuggestTitle: "다음 주문 때 참고",
    postSubmitSuggestHint: "아래 프로모션은 아직 가능합니다. 지금 1박스를 담아 다음 주문을 시작하세요.",
    browseMoreWeeklyPicks: "프로모션 보기",
    logout: "로그아웃",
    customerInfo: "고객 정보",
    show: "보기",
    hide: "숨기기",
    phone: "전화번호 (선택)",
    orderEmail: "주문 이메일",
    orderEmailHint: "주문이 이 주소로 전송됩니다. 기본: elin@rheebros.com",
    orderEmailInvalid: "올바른 이메일 주소를 입력하세요.",
    note: "메모 (선택)",
    searchMode: "빠른 주문",
    searchModeHint: "SKU·바코드·품명 입력 — 항목 선택 후 수량을 넣고 카트에 담으세요.",
    quickOrderEmptyHint: "위 검색창에 SKU를 입력하거나 스캔하세요.",
    quickOrderPickSku: "아래 목록에서 선택하거나 «카트에 담기»를 누르세요.",
    quickOrderMatches: "일치 {count}건",
    quickOrderShowMore: "{count}건 더 보기",
    quickOrderShowLess: "접기",
    quickOrderKeyboardHint: "↑↓ 일치 항목 선택 · +/- 수량 · Enter 담기",
    quickOrderFrequent: "인보이스 자주 주문",
    quickOrderPicks: "빠른 선택",
    catalogMode: "카탈로그 주문",
    promotionMode: "프로모션",
    newItemsMode: "신상품",
    newItemsHero: "Admin → Products에서 「신상품」으로 체크한 SKU만 표시됩니다. JUST ADDED는 빨간 배지입니다.",
    noNewItems: "현재 신상품이 없습니다.",
    addAllNewItemsOneCase: "신상품 각 1박스 추가",
    promotionHint: "프로모션 상품 — 박스 수량을 입력해 카트에 담으세요.",
    loadingPromotions: "프로모션을 불러오는 중...",
    noPromotions: "등록된 프로모션이 없습니다.",
    promoBadge: "할인",
    promoPrice: "프로모션 가격",
    promoRemaining: "남음",
    promoSoldOut: "품절",
    promoDateRange: "유효기간",
    promoBuyXGetY: "Buy {buy} Get {free} FREE",
    promoVolumeTiers: "수량별 단가",
    promoBuyXGetYPackHint: "1세트 = {pack}박스 (구매+무료)",
    promoBogoQtyWarning: "{sku}: Buy {buy} Get {free} — 수량이 {pack}박스 세트가 아닙니다.",
    promoTierQtyWarning: "{sku}: 수량 {qty} — 최저 구간({min}{cs}) 미달입니다.",
    casesAbbr: "cs",
    promoQtyLimit: "프로모션 한정",
    promoLimitAlert: "{sku} 프로모션 {qty}박스만 남았습니다.",
    promoReviewReminder: "프로모션 상품이 아직 없습니다. 제출 전에 확인하시겠습니까?",
    viewPromotions: "프로모션 보기",
    clearanceMode: "임박 특가",
    clearanceHint: "유통기한 임박 상품(있는 그대로 판매). 반품·환불 불가, 확인 후 주문해 주세요.",
    loadingClearance: "임박 상품 불러오는 중...",
    noClearance: "등록된 임박 상품이 없습니다.",
    clearanceBadge: "임박",
    clearanceNoReturn: "반품·환불 불가",
    clearancePolicyReviewNote: "주문에 임박 상품이 포함되어 있습니다. 반품·환불 불가입니다.",
    clearancePrice: "특가",
    invoicePrice: "고객 단가",
    clearanceExpiry: "유통기한",
    clearanceRemaining: "남음",
    clearanceSoldOut: "품절",
    clearanceDaysLeft: "{days}일 남음",
    clearanceQtyLimit: "재고 한정",
    clearanceLimitAlert: "{sku} 임박 재고 {qty}박스만 남았습니다.",
    clearanceReviewReminder: "임박(있는 그대로) 상품 {count}개가 있습니다. 제출 전에 확인하시겠습니까?",
    viewClearance: "임박 보기",
    clearanceQtyWarning: "{sku} 임박 남은 수량은 {qty}입니다.",
    newItemsReviewReminder: "현재 신상품 {count}개가 있습니다. 제출 전에 확인하시겠습니까?",
    viewNewItems: "신상품 보기",
    addItems: "빠른 주문",
    availableOnly: "주문 가능 상품만 보기",
    favoritesOnly: "즐겨찾기만",
    addFavorite: "즐겨찾기 추가",
    removeFavorite: "즐겨찾기 해제",
    noFavorites: "즐겨찾기가 없습니다. 상품의 별을 눌러 저장하세요.",
    skuItem: "SKU / 상품",
    qty: "수량",
    addItem: "카트에 담기",
    catalogSearch: "전체 상품 검색...",
    recent: "자주 주문",
    history: "지난 주문",
    historyChipHint: "이전 주문을 빠르게 다시 담기",
    historyModalHint: "주문을 고른 뒤 다시 주문을 눌러 카트에 담으세요.",
    reorder: "다시 주문",
    orderCart: "카트",
    noItems: "아직 추가된 상품이 없습니다.",
    clearAll: "전체 삭제",
    clearOrder: "주문 삭제",
    remove: "삭제",
    downloadCsv: "CSV 다운로드",
    uploadCsv: "CSV 업로드",
    submitOrder: "주문 확정",
    submitting: "주문 중...",
    unavailable: "현재 주문할 수 없는 상품입니다",
    orderNotAvailable: "주문 불가",
    enterSku: "SKU를 입력해 주세요.",
    duplicate: "이미 카트에 있습니다.\n\n다시 추가하시겠습니까?",
    clearConfirm: "현재 주문을 모두 삭제하시겠습니까?",
    cleared: "현재 주문이 삭제되었습니다.",
    addAtLeast: "상품을 최소 1개 추가해 주세요.",
    submitConfirm: "이 주문을 확정하시겠습니까?",
    accountNo: "거래처 번호",
    storeName: "매장명",
    items: "상품 수",
    ref: "주문번호",
    loadedDraft: "마지막 저장된 주문을 불러왔습니다.",
    csvEmpty: "CSV가 비어 있습니다.",
    noValidRows: "주문 가능한 유효한 SKU/Qty 행이 없습니다.",
    orderSuccess: "주문이 완료되었습니다.",
    failedSubmit: "주문 실패.",
    size: "규격",
    limited: "한정",
    pallet: "팔레트",
    selected: "선택됨",
    allOrderable: "카탈로그 주문",
    noMatches: "검색 결과가 없습니다.",
    tapAdd: "추가 버튼 또는 Enter",
    add: "추가",
    inCart: "선택됨",
    selectedOnly: "선택 상품만",
    showing: "표시",
    loadMore: "더 보기",
    cartSummary: "카트",
    cases: "박스",
    lines: "항목",
    reviewCart: "카트 검토",
    reviewOrder: "주문 검토",
    reviewWarnings: "다시 확인해 주세요",
    reviewWarningsHint: "주문은 그대로 진행할 수 있습니다. 수량만 확인하세요.",
    skipSection: "건너뛰기",
    skipWeeklyUpsell: "프로모션 건너뛰기",
    skipClearanceUpsell: "임박 추천 건너뛰기",
    highQtyWarning: "{sku} 수량이 큽니다: {qty}.",
    limitedQtyWarning: "{sku} 한정 수량은 {qty}입니다.",
    promoQtyWarning: "{sku} 프로모션 남은 수량은 {qty}입니다.",
    statusWarning: "{sku} 상태는 {status}입니다.",
    unavailableMissingSku: "{sku} 를 카탈로그에서 찾을 수 없습니다.",
    unavailableInCartTitle: "주문할 수 없는 상품이 있습니다",
    unavailableInCartHint:
      "주문 불가 SKU입니다(주문 가능: NORMAL / TBD). 삭제 후 나머지 장바구니는 그대로 주문할 수 있습니다.",
    removeUnavailable: "주문 불가 상품 삭제",
    removeUnavailableAndSubmit: "삭제 후 주문하기",
    confirmSubmitBlocked: "먼저 주문 불가 상품을 삭제하세요",
    unavailableRemoved: "주문 불가 상품 {count}개를 삭제했습니다.",
    confirmSubmit: "확인 후 주문",
    orderSubmitted: "주문 완료",
    done: "완료",
    showCart: "카트 보기",
    hideCart: "카트 숨기기",
    searchPlaceholder: "SKU, UPC, 상품명, 브랜드, 바코드",
    catalogCount: "개 상품",
    quickAdd: "빠른 추가",
    close: "닫기",
    back: "뒤로",
    brand: "브랜드",
    allBrands: "전체 브랜드",
    category: "카테고리",
    recommended: "추천",
    newItems: "신상품",
    listPrice: "표시 가격",
    justAdded: "방금 등록",
    addedDate: "등록",
    publishedDate: "게시",
    comingDate: "입고 예정",
    showFilters: "필터",
    hideFilters: "필터 숨기기",
    editProduct: "수정",
    viewDetails: "보기",
    hideDetails: "숨기기",
    moreBrandsPick: "다른 브랜드…",
    enterFullscreen: "전체 화면",
    exitFullscreen: "전체 화면 종료",
    scanBarcode: "바코드 스캔",
    scanBarcodeTitle: "바코드 스캔",
    scanBarcodeHint: "바코드를 프레임 안에 맞추고 잠시 고정하세요. 안 되면 가까이 대 보세요.",
    scanBarcodeCameraError: "카메라를 사용할 수 없습니다. 권한을 확인하거나 직접 입력하세요.",
    scanBarcodeTorchOn: "조명 켜기",
    scanBarcodeTorchOff: "조명 끄기",
  },
  vi: {
    title: "Đặt hàng cửa hàng",
    weeklyPicksHero: "Khuyến mãi hiện tại — bấm + để thêm thùng vào giỏ.",
    addAllWeeklyPicksOneCase: "Thêm 1 thùng mỗi mặt hàng khuyến mãi",
    addAllClearanceOneCase: "Thêm 1 thùng mỗi mặt hàng thanh lý",
    missingWeeklyPicksTitle: "Chưa có trong giỏ — khuyến mãi",
    missingClearancePicksTitle: "Chưa có trong giỏ — thanh lý",
    addAllMissingPicks: "Thêm tất cả ({count} · mỗi mặt 1 thùng)",
    addOneCase: "+ 1 thùng",
    recommendedStripTitle: "Gợi ý cho bạn",
    hideSuggested: "Ẩn",
    showSuggested: "Hiện gợi ý",
    addMissingPicksBar: "Thêm {count} khuyến mãi (+1 thùng mỗi món)",
    addMissingClearanceBar: "Thêm {count} thanh lý (+1 thùng mỗi món)",
    roundUpBogo: "Đủ bộ khuyến mãi ({pack} thùng)",
    quickAddSelected: "Đặt số lượng cho SKU đang chọn",
    jumpToCart: "Xem giỏ hàng",
    modeTabMissing: "+{count}",
    postSubmitAddAll: "Thêm tất cả ({count} · mỗi món 1 thùng)",
    cartSalesSummary: "KM {weekly} · thanh lý {clearance}",
    postSubmitSuggestTitle: "Gợi ý cho lần sau",
    postSubmitSuggestHint: "Khuyến mãi vẫn còn — thêm 1 thùng ngay để bắt đầu đơn tiếp theo.",
    browseMoreWeeklyPicks: "Xem khuyến mãi",
    logout: "Đăng xuất",
    customerInfo: "Thông tin khách hàng",
    show: "Mở rộng",
    hide: "Thu gọn",
    phone: "Điện thoại (tùy chọn)",
    orderEmail: "Email nhận đơn",
    orderEmailHint: "Đơn hàng gửi tới địa chỉ này. Mặc định: elin@rheebros.com",
    orderEmailInvalid: "Vui lòng nhập email hợp lệ.",
    note: "Ghi chú (tùy chọn)",
    searchMode: "Đặt nhanh",
    searchModeHint: "Nhập SKU, mã vạch hoặc tên — chọn mục, đặt số lượng, thêm vào giỏ.",
    quickOrderEmptyHint: "Nhập hoặc quét SKU ở ô tìm kiếm phía trên.",
    quickOrderPickSku: "Chọn mục bên dưới hoặc bấm Thêm vào giỏ.",
    quickOrderMatches: "{count} kết quả",
    quickOrderShowMore: "Xem thêm {count}",
    quickOrderShowLess: "Thu gọn",
    quickOrderKeyboardHint: "↑↓ chọn kết quả · +/- số lượng · Enter thêm vào giỏ",
    quickOrderFrequent: "Thường có trên hóa đơn",
    quickOrderPicks: "Chọn nhanh",
    catalogMode: "Đặt theo danh mục",
    promotionMode: "Khuyến mãi",
    newItemsMode: "Hàng mới",
    newItemsHero: "Chỉ SKU bạn đánh dấu New items trong Admin → Products. JUST ADDED hiện nhãn đỏ.",
    noNewItems: "Hiện chưa có hàng mới.",
    addAllNewItemsOneCase: "Thêm 1 thùng mỗi mã mới",
    promotionHint: "Khuyến mãi nổi bật — nhập số thùng để thêm vào giỏ.",
    loadingPromotions: "Đang tải khuyến mãi...",
    noPromotions: "Chưa có chương trình khuyến mãi.",
    promoBadge: "KM",
    promoPrice: "Giá khuyến mãi",
    promoRemaining: "Còn lại",
    promoSoldOut: "Hết hàng",
    promoDateRange: "Hiệu lực",
    promoBuyXGetY: "Mua {buy} tặng {free}",
    promoVolumeTiers: "GIÁ THEO SỐ LƯỢNG",
    promoBuyXGetYPackHint: "Mỗi bộ = {pack} thùng (mua + tặng)",
    promoBogoQtyWarning: "{sku}: Mua {buy} tặng {free} — số lượng chưa đủ bộ {pack} thùng.",
    promoTierQtyWarning: "{sku}: SL {qty} chưa đạt bậc thấp nhất ({min} {cs}).",
    casesAbbr: "th",
    promoQtyLimit: "Giới hạn KM",
    promoLimitAlert: "Chỉ còn {qty} thùng khuyến mãi cho {sku}.",
    promoReviewReminder: "Bạn chưa thêm sản phẩm khuyến mãi. Xem trước khi gửi đơn?",
    viewPromotions: "Xem khuyến mãi",
    clearanceMode: "Thanh lý",
    clearanceHint: "Hàng gần hết hạn — bán nguyên trạng. Không đổi trả, không hoàn tiền.",
    loadingClearance: "Đang tải hàng thanh lý...",
    noClearance: "Chưa có hàng thanh lý.",
    clearanceBadge: "THANH LÝ",
    clearanceNoReturn: "Không đổi trả · không hoàn tiền",
    clearancePolicyReviewNote: "Đơn có hàng thanh lý — không đổi trả, không hoàn tiền.",
    clearancePrice: "Giá thanh lý",
    invoicePrice: "Giá của bạn",
    clearanceExpiry: "Hết hạn",
    clearanceRemaining: "Còn",
    clearanceSoldOut: "Hết hàng",
    clearanceDaysLeft: "Còn {days} ngày",
    clearanceQtyLimit: "Giới hạn kho",
    clearanceLimitAlert: "Chỉ còn {qty} thùng thanh lý cho {sku}.",
    clearanceReviewReminder: "Có {count} mặt hàng sắp hết hạn. Xem trước khi gửi đơn?",
    viewClearance: "Xem thanh lý",
    clearanceQtyWarning: "{sku} thanh lý còn {qty}.",
    newItemsReviewReminder: "Hiện có {count} hàng mới. Xem trước khi gửi đơn?",
    viewNewItems: "Xem hàng mới",
    addItems: "Đặt nhanh",
    availableOnly: "Chỉ hiện SKU có thể đặt",
    favoritesOnly: "Chỉ yêu thích",
    addFavorite: "Thêm yêu thích",
    removeFavorite: "Bỏ yêu thích",
    noFavorites: "Chưa có yêu thích. Chạm ngôi sao trên SKU để lưu.",
    skuItem: "SKU / Sản phẩm",
    qty: "Số lượng",
    addItem: "Thêm vào giỏ",
    catalogSearch: "Tìm tất cả sản phẩm…",
    recent: "Hay đặt",
    history: "Đơn trước",
    historyChipHint: "Chạm để đặt lại đơn hàng trước",
    historyModalHint: "Chọn đơn rồi bấm Đặt lại để thêm vào giỏ.",
    reorder: "Đặt lại",
    orderCart: "Giỏ hàng",
    noItems: "Chưa có sản phẩm trong giỏ.",
    clearAll: "Xóa hết",
    clearOrder: "Xóa đơn",
    remove: "Xóa",
    downloadCsv: "Tải CSV",
    uploadCsv: "Tải lên CSV",
    submitOrder: "Xác nhận đơn",
    submitting: "Đang đặt…",
    unavailable: "Sản phẩm hiện không thể đặt",
    orderNotAvailable: "Không khả dụng",
    enterSku: "Vui lòng nhập SKU.",
    duplicate: "đã có trong giỏ.\n\nBạn có muốn thêm lại không?",
    clearConfirm: "Xác nhận xóa toàn bộ đơn hiện tại?",
    cleared: "Đã xóa đơn hiện tại.",
    addAtLeast: "Vui lòng thêm ít nhất một SKU.",
    submitConfirm: "Xác nhận đặt đơn này?",
    accountNo: "Mã khách",
    storeName: "Tên cửa hàng",
    items: "Dòng hàng",
    ref: "Mã tham chiếu",
    loadedDraft: "Đã tải bản nháp đã lưu.",
    csvEmpty: "File CSV trống.",
    noValidRows: "Không tìm thấy dòng SKU/số lượng hợp lệ.",
    orderSuccess: "Đặt hàng thành công.",
    failedSubmit: "Đặt hàng thất bại.",
    size: "Quy cách",
    limited: "Giới hạn",
    pallet: "Palet",
    selected: "Đã chọn",
    allOrderable: "Đặt theo danh mục",
    noMatches: "Không có SKU phù hợp.",
    tapAdd: "Chạm «Thêm» hoặc nhấn Enter",
    add: "Thêm",
    inCart: "Trong giỏ",
    selectedOnly: "Chỉ trong giỏ",
    showing: "Hiển thị",
    loadMore: "Xem thêm",
    cartSummary: "Giỏ",
    cases: "thùng",
    lines: "dòng",
    reviewCart: "Xem giỏ",
    reviewOrder: "Xem lại đơn",
    reviewWarnings: "Vui lòng kiểm tra lại",
    reviewWarningsHint: "Bạn vẫn có thể đặt hàng — chỉnh số thùng nếu cần.",
    skipSection: "Bỏ qua",
    skipWeeklyUpsell: "Bỏ qua khuyến mãi",
    skipClearanceUpsell: "Bỏ qua gợi ý thanh lý",
    highQtyWarning: "{sku} có số lượng lớn: {qty}.",
    limitedQtyWarning: "{sku} giới hạn là {qty}.",
    promoQtyWarning: "{sku} khuyến mãi còn {qty}.",
    statusWarning: "{sku} trạng thái là {status}.",
    unavailableMissingSku: "Không tìm thấy {sku} trong danh mục.",
    unavailableInCartTitle: "Một số mặt hàng không đặt được",
    unavailableInCartHint:
      "Các SKU này không đặt được (chỉ NORMAL / TBD). Xóa chúng rồi mới gửi đơn; phần còn lại vẫn đặt được.",
    removeUnavailable: "Xóa mặt hàng không khả dụng",
    removeUnavailableAndSubmit: "Xóa rồi đặt hàng",
    confirmSubmitBlocked: "Hãy xóa mặt hàng không khả dụng trước",
    unavailableRemoved: "Đã xóa {count} mặt hàng không khả dụng.",
    confirmSubmit: "Xác nhận đặt hàng",
    orderSubmitted: "Đã đặt hàng",
    done: "Xong",
    showCart: "Mở giỏ",
    hideCart: "Đóng giỏ",
    searchPlaceholder: "SKU, UPC, tên hàng, thương hiệu hoặc barcode",
    catalogCount: "sản phẩm",
    quickAdd: "Thêm nhanh",
    close: "Đóng",
    back: "Quay lại",
    brand: "Thương hiệu",
    allBrands: "Tất cả thương hiệu",
    category: "Danh mục",
    recommended: "Gợi ý",
    newItems: "Hàng mới",
    listPrice: "Giá niêm yết",
    justAdded: "MỚI THÊM",
    addedDate: "Thêm",
    publishedDate: "Đăng",
    comingDate: "Dự kiến có",
    showFilters: "Bộ lọc",
    hideFilters: "Ẩn bộ lọc",
    editProduct: "Sửa",
    viewDetails: "Xem",
    hideDetails: "Ẩn",
    moreBrandsPick: "Thương hiệu khác…",
    enterFullscreen: "Toàn màn hình",
    exitFullscreen: "Thoát toàn màn hình",
    scanBarcode: "Quét mã",
    scanBarcodeTitle: "Quét mã vạch",
    scanBarcodeHint: "Căn mã trong khung và giữ yên. Nếu không đọc được, đưa camera lại gần hơn.",
    scanBarcodeCameraError: "Không thể dùng camera. Kiểm tra quyền hoặc nhập mã thủ công.",
    scanBarcodeTorchOn: "Bật đèn",
    scanBarcodeTorchOff: "Tắt đèn",
  },
} as const;

export type OrderCopy = typeof copy;
