export const copy = {
  en: {
    title: "Customer Order",
    logout: "Logout",
    customerInfo: "Customer Info",
    show: "Show",
    hide: "Hide",
    phone: "Phone (Optional)",
    note: "Note (Optional)",
    searchMode: "Search Order",
    catalogMode: "Catalog Order",
    promotionMode: "Promotions",
    promotionHint: "Featured items — add qty and they go to your cart.",
    loadingPromotions: "Loading promotions...",
    noPromotions: "No promotions configured yet.",
    promoBadge: "SALE",
    promoPrice: "Promo price",
    promoRemaining: "Left",
    promoSoldOut: "Sold out",
    promoDateRange: "Valid",
    promoQtyLimit: "Promo limit",
    promoLimitAlert: "Only {qty} promo cases left for {sku}.",
    promoReviewReminder: "There are {count} promotion items available. Want to check them before submitting?",
    viewPromotions: "View promotions",
    clearanceMode: "Clearance",
    clearanceHint: "Near-expiry sell-as-is items — expiry date and price shown. Add qty to cart.",
    loadingClearance: "Loading clearance items...",
    noClearance: "No clearance items right now.",
    clearanceBadge: "SELL AS IS",
    clearancePrice: "Clearance price",
    clearanceExpiry: "Expires",
    clearanceRemaining: "Left",
    clearanceSoldOut: "Sold out",
    clearanceDaysLeft: "{days} days left",
    clearanceQtyLimit: "Stock limit",
    clearanceLimitAlert: "Only {qty} clearance cases left for {sku}.",
    clearanceReviewReminder: "There are {count} clearance (sell-as-is) items available. Check them before submitting?",
    viewClearance: "View clearance",
    clearanceQtyWarning: "{sku} clearance stock left is {qty}.",
    newItemsReviewReminder: "There are {count} new items available. Want to check them before submitting?",
    viewNewItems: "View new items",
    addItems: "Add Items",
    availableOnly: "Show available items only",
    skuItem: "SKU / Item",
    qty: "Qty",
    addItem: "Add Item",
    catalogSearch: "Search all orderable items...",
    recent: "Recently Ordered",
    history: "Order History",
    reorder: "Reorder",
    orderCart: "Order Cart",
    noItems: "No items added yet.",
    clearAll: "Clear All",
    clearOrder: "Clear Order",
    remove: "Remove",
    downloadCsv: "Download CSV",
    uploadCsv: "Upload CSV",
    submitOrder: "Submit Order",
    submitting: "Submitting...",
    unavailable: "This item is currently unavailable",
    enterSku: "Please enter SKU.",
    duplicate: "is already in cart.\n\nDo you want to add it again?",
    clearConfirm: "Please confirm clear current order.",
    cleared: "Current order cleared.",
    addAtLeast: "Please add at least one item.",
    submitConfirm: "Submit this order?",
    accountNo: "Account",
    storeName: "Store",
    items: "Items",
    ref: "Ref",
    loadedDraft: "Last saved draft loaded.",
    csvEmpty: "CSV is empty.",
    noValidRows: "No valid orderable SKU/Qty rows found.",
    orderSuccess: "Order submitted successfully.",
    failedSubmit: "Failed to submit order.",
    size: "Size",
    limited: "Limited",
    pallet: "Pallet",
    selected: "Selected",
    allOrderable: "All Orderable Items",
    noMatches: "No items match your search.",
    tapAdd: "Tap Add or press Enter",
    add: "Add",
    inCart: "In cart",
    selectedOnly: "In cart only",
    showing: "Showing",
    loadMore: "Load more",
    cartSummary: "Cart",
    cases: "cases",
    lines: "lines",
    reviewCart: "Review",
    reviewOrder: "Review order",
    reviewWarnings: "Please double-check",
    highQtyWarning: "{sku} has a large qty: {qty}.",
    limitedQtyWarning: "{sku} limited qty is {qty}.",
    promoQtyWarning: "{sku} promo left is {qty}.",
    statusWarning: "{sku} status is {status}.",
    confirmSubmit: "Confirm & submit",
    orderSubmitted: "Order submitted",
    done: "Done",
    showCart: "Show cart",
    hideCart: "Hide cart",
    searchPlaceholder: "SKU, name, brand, or barcode",
    catalogCount: "orderable items",
    quickAdd: "Quick add",
    close: "Close",
    back: "Back",
    brand: "Brand",
    allBrands: "All brands",
    category: "Category",
    recommended: "Recommended",
    newItems: "New items",
    showFilters: "Filters",
    hideFilters: "Hide filters",
    editProduct: "Edit",
    viewDetails: "View",
    hideDetails: "Hide",
    moreBrandsPick: "More brands…",
  },
  zh: {
    title: "客户订单",
    logout: "登出",
    customerInfo: "客户信息",
    show: "展开",
    hide: "收起",
    phone: "电话（可选）",
    note: "备注（可选）",
    searchMode: "搜索下单",
    catalogMode: "商品目录下单",
    promotionMode: "促销推荐",
    promotionHint: "精选促销商品，输入数量即可加入购物车。",
    loadingPromotions: "正在加载促销商品...",
    noPromotions: "暂无促销活动。",
    promoBadge: "促销",
    promoPrice: "促销价",
    promoRemaining: "剩余",
    promoSoldOut: "已售罄",
    promoDateRange: "有效期",
    promoQtyLimit: "促销限量",
    promoLimitAlert: "{sku} 促销仅剩 {qty} 箱。",
    promoReviewReminder: "现在有 {count} 个促销商品。提交前要不要看一下？",
    viewPromotions: "查看促销",
    clearanceMode: "临期特价",
    clearanceHint: "临期按现状出售商品，显示过期日期与特价。输入数量加入购物车。",
    loadingClearance: "正在加载临期商品...",
    noClearance: "暂无临期商品。",
    clearanceBadge: "临期",
    clearancePrice: "特价",
    clearanceExpiry: "过期日",
    clearanceRemaining: "剩余",
    clearanceSoldOut: "已售罄",
    clearanceDaysLeft: "还剩 {days} 天",
    clearanceQtyLimit: "库存限量",
    clearanceLimitAlert: "{sku} 临期仅剩 {qty} 箱。",
    clearanceReviewReminder: "现在有 {count} 个临期（按现状出售）商品。提交前要不要看一下？",
    viewClearance: "查看临期",
    clearanceQtyWarning: "{sku} 临期剩余 {qty}。",
    newItemsReviewReminder: "现在有 {count} 个新品。提交前要不要看一下？",
    viewNewItems: "查看新品",
    addItems: "添加商品",
    availableOnly: "只显示可下单商品",
    skuItem: "SKU / 商品",
    qty: "数量",
    addItem: "添加",
    catalogSearch: "搜索全部可下单商品...",
    recent: "最近常订",
    history: "订单历史",
    reorder: "再次下单",
    orderCart: "订单购物车",
    noItems: "还没有添加商品。",
    clearAll: "清空",
    clearOrder: "清空订单",
    remove: "删除",
    downloadCsv: "下载 CSV",
    uploadCsv: "上传 CSV",
    submitOrder: "提交订单",
    submitting: "提交中...",
    unavailable: "此商品目前无法下单",
    enterSku: "请输入 SKU。",
    duplicate: "已经在购物车里。\n\n是否还要再添加一次？",
    clearConfirm: "请确认是否清空当前订单？",
    cleared: "当前订单已清空。",
    addAtLeast: "请至少添加一个商品。",
    submitConfirm: "确定提交这个订单吗？",
    accountNo: "客户账号",
    storeName: "店名",
    items: "商品数",
    ref: "编号",
    loadedDraft: "已载入上次保存的草稿。",
    csvEmpty: "CSV 是空的。",
    noValidRows: "没有找到可下单的有效 SKU/Qty。",
    orderSuccess: "订单提交成功。",
    failedSubmit: "订单提交失败。",
    size: "规格",
    limited: "限量",
    pallet: "板数",
    selected: "已选",
    allOrderable: "全部可下单商品",
    noMatches: "没有找到匹配的商品。",
    tapAdd: "点「添加」或按回车",
    add: "添加",
    inCart: "已选",
    selectedOnly: "只看已选",
    showing: "显示",
    loadMore: "加载更多",
    cartSummary: "购物车",
    cases: "箱",
    lines: "项",
    reviewCart: "核对",
    reviewOrder: "核对订单",
    reviewWarnings: "请再确认",
    highQtyWarning: "{sku} 数量较大：{qty}。",
    limitedQtyWarning: "{sku} 限量为 {qty}。",
    promoQtyWarning: "{sku} 促销剩余 {qty}。",
    statusWarning: "{sku} 状态为 {status}。",
    confirmSubmit: "确认提交",
    orderSubmitted: "订单已提交",
    done: "完成",
    showCart: "展开购物车",
    hideCart: "收起购物车",
    searchPlaceholder: "SKU、品名、品牌或条码",
    catalogCount: "个可下单商品",
    quickAdd: "快速添加",
    close: "关闭",
    back: "返回",
    brand: "品牌",
    allBrands: "全部品牌",
    category: "分类",
    recommended: "常买推荐",
    newItems: "新品",
    showFilters: "筛选",
    hideFilters: "收起筛选",
    editProduct: "编辑",
    viewDetails: "查看",
    hideDetails: "收起",
    moreBrandsPick: "更多品牌…",
  },
  ko: {
    title: "고객 주문",
    logout: "로그아웃",
    customerInfo: "고객 정보",
    show: "보기",
    hide: "숨기기",
    phone: "전화번호 (선택)",
    note: "메모 (선택)",
    searchMode: "검색 주문",
    catalogMode: "카탈로그 주문",
    promotionMode: "프로모션",
    promotionHint: "추천 상품 — 수량 입력 시 카트에 추가됩니다.",
    loadingPromotions: "프로모션을 불러오는 중...",
    noPromotions: "등록된 프로모션이 없습니다.",
    promoBadge: "할인",
    promoPrice: "프로모션 가격",
    promoRemaining: "남음",
    promoSoldOut: "품절",
    promoDateRange: "유효기간",
    promoQtyLimit: "프로모션 한정",
    promoLimitAlert: "{sku} 프로모션 {qty}박스만 남았습니다.",
    promoReviewReminder: "현재 프로모션 상품 {count}개가 있습니다. 제출 전에 확인하시겠습니까?",
    viewPromotions: "프로모션 보기",
    clearanceMode: "임박 특가",
    clearanceHint: "유통기한 임박 상품(있는 그대로 판매). 유통기한과 특가가 표시됩니다.",
    loadingClearance: "임박 상품 불러오는 중...",
    noClearance: "등록된 임박 상품이 없습니다.",
    clearanceBadge: "임박",
    clearancePrice: "특가",
    clearanceExpiry: "유통기한",
    clearanceRemaining: "남음",
    clearanceSoldOut: "품절",
    clearanceDaysLeft: "{days}일 남음",
    clearanceQtyLimit: "재고 한정",
    clearanceLimitAlert: "{sku} 임박 재고 {qty}박스만 남았습니다.",
    clearanceReviewReminder: "임박(있는 그대로) 상품 {count}개가 있습니다. 제출 전에 확인하시겠습니까?",
    viewClearance: "임박 보기",
    clearanceQtyWarning: "{sku} 임박 남은 수량은 {qty}입니다.",
    newItemsReviewReminder: "현재 신상품 {count}개가 있습니다. 제출 전에 확인하시겠습니까?",
    viewNewItems: "신상품 보기",
    addItems: "상품 추가",
    availableOnly: "주문 가능 상품만 보기",
    skuItem: "SKU / 상품",
    qty: "수량",
    addItem: "추가",
    catalogSearch: "주문 가능 상품 검색...",
    recent: "최근 주문 상품",
    history: "주문 내역",
    reorder: "다시 주문",
    orderCart: "주문 카트",
    noItems: "아직 추가된 상품이 없습니다.",
    clearAll: "전체 삭제",
    clearOrder: "주문 삭제",
    remove: "삭제",
    downloadCsv: "CSV 다운로드",
    uploadCsv: "CSV 업로드",
    submitOrder: "주문 제출",
    submitting: "제출 중...",
    unavailable: "현재 주문할 수 없는 상품입니다",
    enterSku: "SKU를 입력해 주세요.",
    duplicate: "이미 카트에 있습니다.\n\n다시 추가하시겠습니까?",
    clearConfirm: "현재 주문을 모두 삭제하시겠습니까?",
    cleared: "현재 주문이 삭제되었습니다.",
    addAtLeast: "상품을 최소 1개 추가해 주세요.",
    submitConfirm: "이 주문을 제출하시겠습니까?",
    accountNo: "거래처 번호",
    storeName: "매장명",
    items: "상품 수",
    ref: "주문번호",
    loadedDraft: "마지막 저장된 주문을 불러왔습니다.",
    csvEmpty: "CSV가 비어 있습니다.",
    noValidRows: "주문 가능한 유효한 SKU/Qty 행이 없습니다.",
    orderSuccess: "주문이 성공적으로 제출되었습니다.",
    failedSubmit: "주문 제출 실패.",
    size: "규격",
    limited: "한정",
    pallet: "팔레트",
    selected: "선택됨",
    allOrderable: "전체 주문 가능 상품",
    noMatches: "검색 결과가 없습니다.",
    tapAdd: "추가 버튼 또는 Enter",
    add: "추가",
    inCart: "선택됨",
    selectedOnly: "선택 상품만",
    showing: "표시",
    loadMore: "더 보기",
    cartSummary: "카트",
    cases: "박스",
    lines: "항목",
    reviewCart: "검토",
    reviewOrder: "주문 검토",
    reviewWarnings: "다시 확인해 주세요",
    highQtyWarning: "{sku} 수량이 큽니다: {qty}.",
    limitedQtyWarning: "{sku} 한정 수량은 {qty}입니다.",
    promoQtyWarning: "{sku} 프로모션 남은 수량은 {qty}입니다.",
    statusWarning: "{sku} 상태는 {status}입니다.",
    confirmSubmit: "확인 후 제출",
    orderSubmitted: "주문 완료",
    done: "완료",
    showCart: "카트 보기",
    hideCart: "카트 숨기기",
    searchPlaceholder: "SKU, 상품명, 브랜드, 바코드",
    catalogCount: "개 주문 가능",
    quickAdd: "빠른 추가",
    close: "닫기",
    back: "뒤로",
    brand: "브랜드",
    allBrands: "전체 브랜드",
    category: "카테고리",
    recommended: "추천",
    newItems: "신상품",
    showFilters: "필터",
    hideFilters: "필터 숨기기",
    editProduct: "수정",
    viewDetails: "보기",
    hideDetails: "숨기기",
    moreBrandsPick: "다른 브랜드…",
  },
  vi: {
    title: "Đặt hàng khách",
    logout: "Đăng xuất",
    customerInfo: "Thông tin khách hàng",
    show: "Mở rộng",
    hide: "Thu gọn",
    phone: "Điện thoại (tùy chọn)",
    note: "Ghi chú (tùy chọn)",
    searchMode: "Đặt theo tìm kiếm",
    catalogMode: "Đặt theo danh mục",
    promotionMode: "Khuyến mãi",
    promotionHint: "Sản phẩm nổi bật — nhập số lượng để thêm vào giỏ.",
    loadingPromotions: "Đang tải khuyến mãi...",
    noPromotions: "Chưa có chương trình khuyến mãi.",
    promoBadge: "KM",
    promoPrice: "Giá khuyến mãi",
    promoRemaining: "Còn lại",
    promoSoldOut: "Hết hàng",
    promoDateRange: "Hiệu lực",
    promoQtyLimit: "Giới hạn KM",
    promoLimitAlert: "Chỉ còn {qty} thùng khuyến mãi cho {sku}.",
    promoReviewReminder: "Hiện có {count} sản phẩm khuyến mãi. Xem trước khi gửi đơn?",
    viewPromotions: "Xem khuyến mãi",
    clearanceMode: "Sắp hết hạn",
    clearanceHint: "Hàng gần hết hạn — bán nguyên trạng. Hiển thị ngày hết hạn và giá thanh lý.",
    loadingClearance: "Đang tải hàng thanh lý...",
    noClearance: "Chưa có hàng thanh lý.",
    clearanceBadge: "THANH LÝ",
    clearancePrice: "Giá thanh lý",
    clearanceExpiry: "Hết hạn",
    clearanceRemaining: "Còn",
    clearanceSoldOut: "Hết hàng",
    clearanceDaysLeft: "Còn {days} ngày",
    clearanceQtyLimit: "Giới hạn kho",
    clearanceLimitAlert: "Chỉ còn {qty} thùng thanh lý cho {sku}.",
    clearanceReviewReminder: "Có {count} mặt hàng sắp hết hạn. Xem trước khi gửi đơn?",
    viewClearance: "Xem thanh lý",
    clearanceQtyWarning: "{sku} thanh lý còn {qty}.",
    newItemsReviewReminder: "Hiện có {count} hàng mới. Xem trước khi gửi đơn?",
    viewNewItems: "Xem hàng mới",
    addItems: "Thêm hàng",
    availableOnly: "Chỉ hiện SKU có thể đặt",
    skuItem: "SKU / Sản phẩm",
    qty: "Số lượng",
    addItem: "Thêm",
    catalogSearch: "Tìm tất cả SKU có thể đặt…",
    recent: "Đã đặt gần đây",
    history: "Lịch sử đơn",
    reorder: "Đặt lại",
    orderCart: "Giỏ hàng đơn",
    noItems: "Chưa có sản phẩm trong giỏ.",
    clearAll: "Xóa hết",
    clearOrder: "Xóa đơn",
    remove: "Xóa",
    downloadCsv: "Tải CSV",
    uploadCsv: "Tải lên CSV",
    submitOrder: "Gửi đơn",
    submitting: "Đang gửi…",
    unavailable: "Sản phẩm hiện không thể đặt",
    enterSku: "Vui lòng nhập SKU.",
    duplicate: "đã có trong giỏ.\n\nBạn có muốn thêm lại không?",
    clearConfirm: "Xác nhận xóa toàn bộ đơn hiện tại?",
    cleared: "Đã xóa đơn hiện tại.",
    addAtLeast: "Vui lòng thêm ít nhất một SKU.",
    submitConfirm: "Gửi đơn này?",
    accountNo: "Mã khách",
    storeName: "Tên cửa hàng",
    items: "Dòng hàng",
    ref: "Mã tham chiếu",
    loadedDraft: "Đã tải bản nháp đã lưu.",
    csvEmpty: "File CSV trống.",
    noValidRows: "Không tìm thấy dòng SKU/số lượng hợp lệ.",
    orderSuccess: "Gửi đơn thành công.",
    failedSubmit: "Gửi đơn thất bại.",
    size: "Quy cách",
    limited: "Giới hạn",
    pallet: "Palet",
    selected: "Đã chọn",
    allOrderable: "Tất cả SKU có thể đặt",
    noMatches: "Không có SKU phù hợp.",
    tapAdd: "Chạm «Thêm» hoặc nhấn Enter",
    add: "Thêm",
    inCart: "Trong giỏ",
    selectedOnly: "Chỉ trong giỏ",
    showing: "Hiển thị",
    loadMore: "Xem thêm",
    cartSummary: "Giỏ",
    cases: "thùng",
    lines: "dòng",
    reviewCart: "Xem lại",
    reviewOrder: "Xem lại đơn",
    reviewWarnings: "Vui lòng kiểm tra lại",
    highQtyWarning: "{sku} có số lượng lớn: {qty}.",
    limitedQtyWarning: "{sku} giới hạn là {qty}.",
    promoQtyWarning: "{sku} khuyến mãi còn {qty}.",
    statusWarning: "{sku} trạng thái là {status}.",
    confirmSubmit: "Xác nhận và gửi",
    orderSubmitted: "Đã gửi đơn",
    done: "Xong",
    showCart: "Mở giỏ",
    hideCart: "Đóng giỏ",
    searchPlaceholder: "SKU, tên hàng, thương hiệu hoặc barcode",
    catalogCount: "SKU có thể đặt",
    quickAdd: "Thêm nhanh",
    close: "Đóng",
    back: "Quay lại",
    brand: "Thương hiệu",
    allBrands: "Tất cả thương hiệu",
    category: "Danh mục",
    recommended: "Gợi ý",
    newItems: "Hàng mới",
    showFilters: "Bộ lọc",
    hideFilters: "Ẩn bộ lọc",
    editProduct: "Sửa",
    viewDetails: "Xem",
    hideDetails: "Ẩn",
    moreBrandsPick: "Thương hiệu khác…",
  },
} as const;

export type OrderCopy = typeof copy;
